# Generated by Django 5.0.4 on 2024-08-07 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authservice', '0002_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=255),
        ),
    ]
