# Generated by Django 5.0.4 on 2024-08-07 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authservice', '0003_alter_customuser_options_customuser_date_joined_and_more'),
        ('authservice', '0003_alter_customuser_phone_number'),
    ]

    operations = [
    ]
