# Generated by Django 5.0.4 on 2024-10-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('failed', 'failed')], max_length=20),
        ),
    ]
