# Generated by Django 5.0.4 on 2024-08-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastepickup',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='wastepickup',
            name='pending',
        ),
        migrations.RemoveField(
            model_name='wastepickup',
            name='picked_up',
        ),
        migrations.AddField(
            model_name='wastepickup',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Picked up', 'Picked up'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
