# Generated by Django 5.0.4 on 2024-08-06 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastebin',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='wastebin',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='wastebin',
            name='picked_up',
        ),
        migrations.RemoveField(
            model_name='wastebin',
            name='reward_points',
        ),
        migrations.RemoveField(
            model_name='wastebin',
            name='type_of_waste',
        ),
        migrations.RemoveField(
            model_name='wastebin',
            name='weight',
        ),
        migrations.AddField(
            model_name='wastebin',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wastecategory',
            name='name',
            field=models.CharField(choices=[('recyclable', 'Recyclable'), ('non-recyclable', 'Non-Recyclable')], max_length=20),
        ),
        migrations.CreateModel(
            name='wasteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('points', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.wastebin')),
                ('type_of_waste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.wastecategory')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
