# Generated by Django 5.0.4 on 2024-09-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveSensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_id', models.CharField(max_length=120)),
                ('humidity', models.FloatField()),
                ('waste_height', models.FloatField()),
                ('temperature', models.FloatField()),
                ('weight', models.FloatField()),
                ('batt_value', models.FloatField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.DeleteModel(
            name='SensorData',
        ),
    ]
