# Generated by Django 5.0.4 on 2024-08-09 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wastepickup',
            old_name='confirmed',
            new_name='completed',
        ),
    ]
