# Generated by Django 5.1.5 on 2025-03-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='department',
            field=models.CharField(default='admin', max_length=255),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='employee_id',
            field=models.CharField(default='ib_00010', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='location',
            field=models.CharField(default='Lagos', max_length=300),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='location',
            field=models.CharField(default='Lagos', max_length=300),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='department',
            field=models.CharField(default='operations', max_length=255),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='employee_id',
            field=models.CharField(default='ib_001001', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='location',
            field=models.CharField(default='Lagos', max_length=300),
        ),
    ]
