# Generated by Django 5.1.5 on 2025-03-08 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste_mgmt', '0002_adminprofile_department_adminprofile_employee_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wastedata',
            old_name='bin',
            new_name='bin_id',
        ),
    ]
